name: pr-test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        - run: echo "test finished"
